### ISSUE TITLE
Can not open iceworks

### ISSUE THREAD

**Issue by wangiv2** [alibaba/ice#2934]
after update to 2.25.0, can not open iceworks, it show a white blank page as below.
![image](https://user-images.githubusercontent.com/7232767/69248804-e4ab3d80-0be7-11ea-9147-6a2710a3bcd7.png)

**Comment by alvinhui** [comment]
What did you do?

**Comment by wangiv2** [comment]
i got the upgrade alert yesterday and just clicked upgrade the iceworks, i did not do anything else.

**Comment by alvinhui** [comment]
could  you help to take a look `window.__bl.error` what is?

```js
window.__bl.error
```

**Comment by alvinhui** [comment]
Try to enter this value in the console and enter.

**Comment by alvinhui** [comment]
I can not be sure why `__bl.error` is not a function, I submit a PR(https://github.com/alibaba/ice/pull/2939), make sure `__bl.error` is a function before call.

**Comment by alvinhui** [comment]
we will release 2.25.1 as soon as possible.
